" File              : .vimrc
" Author            : Channith Am <amcnith@gmail.com>
" Date              : 19.08.2017
" Last Modified Date: 07.09.2017
" Last Modified By  : Channith Am <amcnith@gmail.com>

set nocompatible        " be iMproved, required                           
filetype off            " required

" set the runtime path to include Vundle and initialize                         
set rtp+=~/.vim/bundle/Vundle.vim                                               
call vundle#begin()


" let Vundle manage Vundle, required                                            
Plugin 'VundleVim/Vundle.vim'
Plugin 'kien/ctrlp.vim'
Plugin 'flazz/vim-colorschemes'
Plugin 'alpertuna/vim-header'
Plugin 'valloric/youcompleteme'
Plugin 'tpope/vim-surround' " Parentheses, brackets, quotes, XML tags,...
Plugin 'jiangmiao/auto-pairs'


" All of your Plugins must be added before the following line
call vundle#end()            " required                                         
filetype plugin indent on    " required


" set color
syntax enable
set t_Co=256
set background=dark
colorscheme solarized
let g:solarized_termtrans=1

let g:header_field_author = 'Channith Am'
let g:header_field_author_email = 'amcnith@gmail.com'
map <F4> :AddHeader<CR>

set title " show the filename in the window titlebar
set showtabline=1
set number
set cursorline
set enc=utf-8   " utf-8 by default
set showmatch   " show matching part of bracket pairs (), [], {}
" Additional mapping for Esc
inoremap jj <Esc>
inoremap jk <Esc>
